version: '3.8'

services:
  database:
    build: ./psql
    env_file:
      - psql_secrets.env
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U sreality_user" ]
      interval: 5s
      timeout: 5s
      retries: 3

  web:
    build: ./flask
    command: uwsgi --socket 0.0.0.0:8080 --protocol=http -w app:app
    env_file:
      - psql_secrets.env
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

  scraper:
    build: ./scrapy
    command: python run_scraper.py
    env_file:
      - psql_secrets.env
    depends_on:
      database:
        condition: service_healthy
